# This is a basic workflow to help you get started with Actions

name: auto build to exe

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags: 
      - v*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install requirements
        run: |
          pip3 install -r requirements.txt
          pip3 install pyinstaller
          

      # Runs a set of commands using the runners shell
      - name: Get exe file
        run: pyinstaller -F playVoice.py
       
      - name: Setup timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneWindows: "China Standard Time" 
        
      - name: Get current time
        id: date
        run: echo "::set-output name=date::$(date +'%m-%d--%H-%M')"
      
      - name: Upload files
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist/playVoice.exe
            ./playVoice.py
          name: ${{ steps.date.outputs.date }}
          tag_name: ${{  github.ref_name }}
